server:
  port: 9000
spring:
  application:
    name: mall-gateway
eureka:
  client:
    service-url:
      defaultZone: http://server1:8001/eureka/

zuul:
  prefix: /mall
  routes:
    mall-goods:
      path: /mall-goods/**
      serverId: mall-goods
      strip-prefix: false
    mall-customer:
      path: /mall-customer/**
      serverId: mall-customer
      strip-prefix: false

gateway:
  rule:
    json: "{id:rateLimitHandler,children:[{id:validateAuthorityHandler:children:[{validateTokenHandler}]}]}"