server:
  port: 8090
  servlet:
    context-path: /mall-payment

spring:
  application:
    name: mall-payment
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
      url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: password
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      tomcat:
        max-active: 10
        min-idle: 5
        initial-size: 5

  mybatis:
    mapper-locations: classpath:mappers/**/*.xml
    type-aliases-package: com.sherlock.mallgoods.model

eureka:
  client:
    service-url:
      defaultZone: http://server1:8001/eureka/

kafka:
  bootstrap-servers: localhost:9092
  producer:
    retries: 0
    batch-size: 16384
    buffer-memory: 33554432
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer